# Generated by Django 4.1.2 on 2022-11-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=35)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=18)),
            ],
        ),
    ]
