# Generated by Django 4.1.2 on 2022-12-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='First name')),
                ('second_name', models.CharField(max_length=35, verbose_name='Second name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('phone', models.CharField(blank=True, max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='client1.persone')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
