# Generated by Django 4.1.2 on 2022-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0002_persone_phone_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persone',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='persone',
            name='phone',
            field=models.CharField(blank=True, max_length=18, verbose_name='Phone number'),
        ),
    ]
