# Generated by Django 4.1.2 on 2022-12-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0003_remove_persone_second_name_alter_persone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
