# Generated by Django 4.1.2 on 2022-12-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0004_alter_persone_name_delete_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persone',
            name='phone',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='client1.persone')),
            ],
        ),
    ]
