# Generated by Django 4.1.2 on 2022-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0005_remove_persone_phone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.IntegerField(max_length=12, verbose_name='Phone'),
        ),
    ]
