# Generated by Django 4.1.2 on 2022-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client1', '0008_persone_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='sum_of_insurence',
            field=models.IntegerField(default=0, verbose_name='Sum of insurence'),
        ),
    ]
